# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: test
    name: Commit
    stages: [pre-commit]
    language: system
    entry: uv run pytest
    pass_filenames: false
    verbose: false
