# See https://pre-commit.com/ for usage and config
repos:
    -   repo: local
        hooks:
            -   id: test
                name: Update requirements.txt
                stages: [ pre-commit ]
                language: system
                entry: uv export --no-hashes --no-dev --format requirements-txt --output-file requirements.txt
                pass_filenames: false
                verbose: false
            -   id: test
                name: Commit
                stages: [ pre-commit ]
                language: system
                entry: uv run pytest
                pass_filenames: false
                verbose: false
